FROM --platform=linux/amd64 condaforge/miniforge3:24.11.3-0
ENV DEBIAN_FRONTEND=noninteractive


#RUN conda create -n docs -c conda-forge make pandoc sphinx nbsphinx jinja2 sphinx-reredirects ipython_genutils furo pygments
#RUN conda export -n docs > /environment_sphinx.yml


COPY environment_sphinx.yml /environment_sphinx.yml
RUN conda env create -y -n docs -f /environment_sphinx.yml

ENV PATH="/opt/conda/envs/docs/bin:$PATH"



